# This is a basic workflow to help you get started with Actions

name: Create markdown indexes

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WIKI_SYNC_SECRET }}
          ref: ${{ github.event.repository.default_branch }}

      # Runs a single command using the runners shell
      - name: Generated Markdown Readmes
        uses: DaanV2/Markdown-Action-Create-Indexes@v2.0.0


      - name: Create pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ env.SYNC_CHANGES_REPO_NAME }}
          destination_branch: ${{ github.event.repository.default_branch }}
          pr_title: "[Chore] - Syncing Wiki changes in ${{ env.SYNC_CHANGES_REPO_NAME }} into default branch"
          pr_body: ":crown: *An automated PR* This is an automated PR to sync this repository's wiki docs with your docs in the repo via a PR."
          pr_label: "docs,automation"
          pr_draft: false
          pr_allow_empty: false
          github_token: ${{ secrets.WIKI_SYNC_SECRET }}

