name: Wiki Content Sync

on:
  push:
    branches:
      - master
      - main
    paths:
      - "Documentation/Wiki/**"
  repository_dispatch:
    types: [docs]
  workflow_dispatch:
  gollum:
  
env:
  GIT_AUTHOR_NAME: Github Actions
  GIT_AUTHOR_EMAIL: action@github.com
  SYNC_CHANGES_REPO_NAME: docs-sync
  MARKDOWN_FOLDER: "Documentation/Wiki/**"

jobs:
   markdown-indexes:
      runs-on: [ ubuntu-latest ]
      steps:
        - uses: actions/checkout@v4.1.1
        
        - name: Markdown action - create indexes
          uses: DaanV2/Markdown-Action-Create-Indexes@v5.0.0
          with:
            folder: ${{ env.MARKDOWN_FOLDER }}
            include: |
              *.pdf
              *.mobi
              *.epub
              *.zip
              *.md
            exclude:
              README.md
              Home.md
        
        - name: Commit and push changes
          run: |
            git config --global user.name 'GitHub Action'
            git config --global user.email 'action@github.com'
            git add ${{ env.MARKDOWN_FOLDER }}
            git commit -m "Automatically add links to Markdown files" || exit 0
            git push
