name: Wiki Indexing

on:
  push:
    branches:
      - master
      - main
    paths:
      - "Documentation/Wiki/**"
  repository_dispatch:
    types: [docs]
  workflow_dispatch:
  gollum:
  
env:
  GIT_AUTHOR_NAME: Github Actions
  GIT_AUTHOR_EMAIL: action@github.com
  SYNC_CHANGES_REPO_NAME: docs-sync
  MARKDOWN_FOLDER: "Documentation/Wiki/"

jobs:
   markdown-indexes:
      runs-on: [ ubuntu-latest ]
      steps:
        - uses: actions/checkout@v4.1.1
        
        - name: Markdown action - create indexes
          uses: DaanV2/Markdown-Action-Create-Indexes@v5.0.0
          with:
            folder: ${{ env.MARKDOWN_FOLDER }}
            include: |
              *.pdf
              *.mobi
              *.epub
              *.zip
              *.md
            exclude:
              README.md
              Home.md

        - name: Pushing to the protected branch 'protected'
          uses: CasperWA/push-protected@v2
          with:
            token: ${{ secrets.WIKI_SYNC_SECRET }}
            branch: main
          
        
